[program:contextengine-models]
directory=/root/ce-services
command=/root/ce-services/run-contextengine-models.sh
autostart=true
autorestart=true
startsecs=10
startretries=3
stopsignal=TERM
stopwaitsecs=30
stopasgroup=true
killasgroup=true
stdout_logfile=/root/ce-services/logs/server.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5
redirect_stderr=true
environment=CE_SERVICE_DIR="/root/ce-services"
